### ISSUE TITLE
Switch to Dropbox API v2

### ISSUE THREAD

**Issue by tomnortonuk** [mre/unicorn#2]
Hi,

I've just followed the installation process, and it appears that V1 of the DropBox API was decommissioned in October 2017.  Do you have any planned updates.  As for now, this code returns:

v1_retired

Many Thanks, Tom

**Comment by mre** [comment]
Hey @tomnortonuk,
that's sad.
I would love to update it to V2, but I don't think I'll find the time.
If you like to take a stab at it, please go ahead.
I'll add some labels and change the title so that others can easily find this issue.
Thanks for the heads-up. 🙂

**Comment by mre** [comment]
If anybody wants to work on this, here's what needs to be done:

1. Remove [benthedesigner/dropbox](https://github.com/mre/unicorn/blob/master/composer.json#L16) form the composer.json, as it is unmaintained.
2. Add a PHP client for Dropbox v2 to the composer.json, e.g. [this one](https://github.com/kunalvarma05/dropbox-php-sdk).
3. Adjust Dropbox usage in the project to use the new library.
